/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosOfflineRouteImport } from './routes/todos-offline'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as PublicChatRouteImport } from './routes/public-chat'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstallPwaRouteImport } from './routes/install-pwa'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminChatRouteImport } from './routes/admin-chat'
import { Route as IndexRouteImport } from './routes/index'

const TodosOfflineRoute = TodosOfflineRouteImport.update({
  id: '/todos-offline',
  path: '/todos-offline',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicChatRoute = PublicChatRouteImport.update({
  id: '/public-chat',
  path: '/public-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallPwaRoute = InstallPwaRouteImport.update({
  id: '/install-pwa',
  path: '/install-pwa',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/admin-chat',
  path: '/admin-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-chat': typeof AdminChatRoute
  '/dashboard': typeof DashboardRoute
  '/health': typeof HealthRoute
  '/install-pwa': typeof InstallPwaRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/public-chat': typeof PublicChatRoute
  '/todos': typeof TodosRoute
  '/todos-offline': typeof TodosOfflineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-chat': typeof AdminChatRoute
  '/dashboard': typeof DashboardRoute
  '/health': typeof HealthRoute
  '/install-pwa': typeof InstallPwaRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/public-chat': typeof PublicChatRoute
  '/todos': typeof TodosRoute
  '/todos-offline': typeof TodosOfflineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-chat': typeof AdminChatRoute
  '/dashboard': typeof DashboardRoute
  '/health': typeof HealthRoute
  '/install-pwa': typeof InstallPwaRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/public-chat': typeof PublicChatRoute
  '/todos': typeof TodosRoute
  '/todos-offline': typeof TodosOfflineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-chat'
    | '/dashboard'
    | '/health'
    | '/install-pwa'
    | '/login'
    | '/profile'
    | '/public-chat'
    | '/todos'
    | '/todos-offline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-chat'
    | '/dashboard'
    | '/health'
    | '/install-pwa'
    | '/login'
    | '/profile'
    | '/public-chat'
    | '/todos'
    | '/todos-offline'
  id:
    | '__root__'
    | '/'
    | '/admin-chat'
    | '/dashboard'
    | '/health'
    | '/install-pwa'
    | '/login'
    | '/profile'
    | '/public-chat'
    | '/todos'
    | '/todos-offline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminChatRoute: typeof AdminChatRoute
  DashboardRoute: typeof DashboardRoute
  HealthRoute: typeof HealthRoute
  InstallPwaRoute: typeof InstallPwaRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  PublicChatRoute: typeof PublicChatRoute
  TodosRoute: typeof TodosRoute
  TodosOfflineRoute: typeof TodosOfflineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos-offline': {
      id: '/todos-offline'
      path: '/todos-offline'
      fullPath: '/todos-offline'
      preLoaderRoute: typeof TodosOfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-chat': {
      id: '/public-chat'
      path: '/public-chat'
      fullPath: '/public-chat'
      preLoaderRoute: typeof PublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install-pwa': {
      id: '/install-pwa'
      path: '/install-pwa'
      fullPath: '/install-pwa'
      preLoaderRoute: typeof InstallPwaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-chat': {
      id: '/admin-chat'
      path: '/admin-chat'
      fullPath: '/admin-chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminChatRoute: AdminChatRoute,
  DashboardRoute: DashboardRoute,
  HealthRoute: HealthRoute,
  InstallPwaRoute: InstallPwaRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  PublicChatRoute: PublicChatRoute,
  TodosRoute: TodosRoute,
  TodosOfflineRoute: TodosOfflineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
